// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"advanced/core/database"
	"advanced/core/environment"
	"advanced/core/middleware"
	"advanced/src/user"
	"github.com/google/wire"
)

// Injectors from injector.go:

// InjectAppConfig
func InjectAppConfig() (*environment.Config, error) {
	config, err := environment.ProvideConfig()
	if err != nil {
		return nil, err
	}
	return config, nil
}

// InjectGRPC digunakan untuk membangun Delivery GRPC User
func InjectUserGRPC() (*user.DeliveryGRPC, error) {
	config, err := environment.ProvideConfig()
	if err != nil {
		return nil, err
	}
	db, err := database.ProvidePostgreSQL(config)
	if err != nil {
		return nil, err
	}
	iUserRepository := user.ProvideUserRepository(db)
	iUserUsecase := user.ProvideUserUsecase(iUserRepository)
	deliveryGRPC := user.ProvideDeliveryGRPC(iUserUsecase)
	return deliveryGRPC, nil
}

// InjectSecurityMiddleware digunakan untuk meng-extract middleware untuk gRPC interceptor
func InjectSecurityMiddleware() (*middleware.SecurityMiddleware, error) {
	config, err := environment.ProvideConfig()
	if err != nil {
		return nil, err
	}
	securityMiddleware := middleware.ProvideMiddleware(config)
	return securityMiddleware, nil
}

// injector.go:

var (
	// CoreModule menyuntikan hal-hal foundation dari aplikasi
	CoreModule = wire.NewSet(environment.ProvideConfig, database.ProvidePostgreSQL, middleware.ProvideMiddleware)

	// UserModule menyuntikan logika domain User
	UserModule = wire.NewSet(user.ProvideUserRepository, user.ProvideUserUsecase, user.ProvideDeliveryGRPC)

	AppModule = wire.NewSet(CoreModule, UserModule)
)
